"""empty message

Revision ID: f58ec39a9172
Revises: 
Create Date: 2019-05-04 14:31:20.302552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f58ec39a9172'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_of_school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_for_pay', sa.String(length=20), nullable=True),
    sa.Column('operator', sa.String(length=20), nullable=True),
    sa.Column('approver', sa.String(length=20), nullable=True),
    sa.Column('use', sa.String(length=50), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('name_collections', sa.String(length=20), nullable=True),
    sa.Column('petty_cash', sa.Integer(), nullable=True),
    sa.Column('methods', sa.String(length=20), nullable=True),
    sa.Column('remarks', sa.String(length=50), nullable=True),
    sa.Column('accountnum', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('cost_of_edu', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cost_of_school_trash',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_for_pay', sa.String(length=20), nullable=True),
    sa.Column('operator', sa.String(length=20), nullable=True),
    sa.Column('approver', sa.String(length=20), nullable=True),
    sa.Column('use', sa.String(length=50), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('name_collections', sa.String(length=20), nullable=True),
    sa.Column('petty_cash', sa.Integer(), nullable=True),
    sa.Column('methods', sa.String(length=20), nullable=True),
    sa.Column('remarks', sa.String(length=50), nullable=True),
    sa.Column('accountnum', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('cost_of_edu', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('income_of_school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('wechat', sa.Integer(), nullable=True),
    sa.Column('use', sa.String(length=50), nullable=True),
    sa.Column('total_cost', sa.Integer(), nullable=True),
    sa.Column('payable_cost', sa.Integer(), nullable=True),
    sa.Column('paid_cost', sa.Integer(), nullable=True),
    sa.Column('supply_cost', sa.Integer(), nullable=True),
    sa.Column('travelling_expenses', sa.Integer(), nullable=True),
    sa.Column('preferential', sa.Integer(), nullable=True),
    sa.Column('methods', sa.String(length=20), nullable=True),
    sa.Column('remarks', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('neibuwaiban', sa.String(length=50), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('income_of_edu', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('income_of_school_trash',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('wechat', sa.Integer(), nullable=True),
    sa.Column('use', sa.String(length=50), nullable=True),
    sa.Column('total_cost', sa.Integer(), nullable=True),
    sa.Column('payable_cost', sa.Integer(), nullable=True),
    sa.Column('paid_cost', sa.Integer(), nullable=True),
    sa.Column('supply_cost', sa.Integer(), nullable=True),
    sa.Column('travelling_expenses', sa.Integer(), nullable=True),
    sa.Column('preferential', sa.Integer(), nullable=True),
    sa.Column('methods', sa.String(length=20), nullable=True),
    sa.Column('remarks', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('neibuwaiban', sa.String(length=50), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('income_of_edu', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recharge_for_phone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_for_recharge', sa.String(length=20), nullable=True),
    sa.Column('operator', sa.String(length=20), nullable=True),
    sa.Column('approver', sa.String(length=20), nullable=True),
    sa.Column('phonenum', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('methods', sa.String(length=20), nullable=True),
    sa.Column('accountnum', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recharge_for_phone_trash',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_for_recharge', sa.String(length=20), nullable=True),
    sa.Column('operator', sa.String(length=20), nullable=True),
    sa.Column('approver', sa.String(length=20), nullable=True),
    sa.Column('phonenum', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('methods', sa.String(length=20), nullable=True),
    sa.Column('accountnum', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recharge_for_phone_trash')
    op.drop_table('recharge_for_phone')
    op.drop_table('income_of_school_trash')
    op.drop_table('income_of_school')
    op.drop_table('cost_of_school_trash')
    op.drop_table('cost_of_school')
    # ### end Alembic commands ###
